// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAsymEnData(arg1) {
  return window['go']['en']['EnRetrieve']['LoadAsymEnData'](arg1);
}

export function LoadEncryptedContent(arg1) {
  return window['go']['en']['EnRetrieve']['LoadEncryptedContent'](arg1);
}

export function RetrieveAsymEn() {
  return window['go']['en']['EnRetrieve']['RetrieveAsymEn']();
}

export function RetrievePGPMsgInfo(arg1) {
  return window['go']['en']['EnRetrieve']['RetrievePGPMsgInfo'](arg1);
}

export function RetrieveSymEn() {
  return window['go']['en']['EnRetrieve']['RetrieveSymEn']();
}
