// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {en} from '../models';

export function LoadAsymEnData(arg1:string):Promise<string>;

export function LoadEncryptedContent(arg1:string):Promise<string>;

export function RetrieveAsymEn():Promise<Array<en.FileInfo>>;

export function RetrieveSymEn():Promise<Array<en.KeyInfo>>;
