// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveHybEn(arg1) {
  return window['go']['en']['KeyStore']['SaveHybEn'](arg1);
}

export function SaveSymEn(arg1, arg2, arg3) {
  return window['go']['en']['KeyStore']['SaveSymEn'](arg1, arg2, arg3);
}
