// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {en} from '../models';

export function SaveHybEn(arg1:en.HybridRequestData):Promise<void>;

export function SaveSymEn(arg1:string,arg2:string,arg3:string):Promise<void>;
