// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptPassphrase(arg1, arg2) {
  return window['go']['hybriddecryption']['HybridPassphraseDecryption']['DecryptPassphrase'](arg1, arg2);
}
