// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EncryptAndSign(arg1) {
  return window['go']['hybenc']['HybEnc']['EncryptAndSign'](arg1);
}

export function TrasformHybEn(arg1) {
  return window['go']['hybenc']['HybEnc']['TrasformHybEn'](arg1);
}
