// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hybenc} from '../models';

export function EncryptAndSign(arg1:hybenc.RequestData):Promise<string>;
