// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectFolder() {
  return window['go']['initializeFolder']['InitializeFolder']['SelectFolder']();
}

export function SetContext(arg1) {
  return window['go']['initializeFolder']['InitializeFolder']['SetContext'](arg1);
}
