// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pgpfs} from '../models';

export function RetrievePgpKeys():Promise<Array<pgpfs.PgpKeyInfo>>;

export function RetrievePgpPrivKey(arg1:string):Promise<string>;

export function RetrievePgpPubKey(arg1:string):Promise<string>;
