// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RetrievePgpKeys() {
  return window['go']['pgpget']['PgpRetrieve']['RetrievePgpKeys']();
}

export function RetrievePgpPrivKey(arg1) {
  return window['go']['pgpget']['PgpRetrieve']['RetrievePgpPrivKey'](arg1);
}

export function RetrievePgpPubKey(arg1) {
  return window['go']['pgpget']['PgpRetrieve']['RetrievePgpPubKey'](arg1);
}
