// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {encryption} from '../models';

export function EncryptAES(arg1:encryption.RequestData):Promise<string>;
