// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1) {
  return window['go']['hybdec']['HybDec']['Decrypt'](arg1);
}

export function DecryptAndValidate(arg1) {
  return window['go']['hybdec']['HybDec']['DecryptAndValidate'](arg1);
}

export function ValidateSignature(arg1) {
  return window['go']['hybdec']['HybDec']['ValidateSignature'](arg1);
}
