// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hybdec} from '../models';

export function DecryptAndValidate(arg1:hybdec.RequestData):Promise<hybdec.ReturnType>;
