// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptAndValidate(arg1) {
  return window['go']['hybdec']['HybDec']['DecryptAndValidate'](arg1);
}
