// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenECC(arg1) {
  return window['go']['pgpgen']['PgpKeysGen']['GenECC'](arg1);
}

export function GenRSA(arg1) {
  return window['go']['pgpgen']['PgpKeysGen']['GenRSA'](arg1);
}

export function GenStoreECC(arg1) {
  return window['go']['pgpgen']['PgpKeysGen']['GenStoreECC'](arg1);
}

export function GenStoreRSA(arg1) {
  return window['go']['pgpgen']['PgpKeysGen']['GenStoreRSA'](arg1);
}

export function GeneratePGPKeys(arg1) {
  return window['go']['pgpgen']['PgpKeysGen']['GeneratePGPKeys'](arg1);
}
