// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pgpgen} from '../models';

export function GenECC(arg1:pgpgen.RequestData):Promise<pgpgen.ReturnType>;

export function GenRSA(arg1:pgpgen.RequestData):Promise<pgpgen.ReturnType>;

export function GenStoreECC(arg1:pgpgen.RequestData):Promise<pgpgen.ReturnType>;

export function GenStoreRSA(arg1:pgpgen.RequestData):Promise<pgpgen.ReturnType>;

export function GeneratePGPKeys(arg1:pgpgen.RequestData):Promise<pgpgen.ReturnType>;
