// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AES128Decryption(arg1) {
  return window['go']['decryption']['Cryptography']['AES128Decryption'](arg1);
}

export function AES192Decryption(arg1) {
  return window['go']['decryption']['Cryptography']['AES192Decryption'](arg1);
}

export function AES256Decryption(arg1) {
  return window['go']['decryption']['Cryptography']['AES256Decryption'](arg1);
}
