// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteHybKey(arg1) {
  return window['go']['keys']['KeyRetrieve']['DeleteHybKey'](arg1);
}

export function DeleteSymKey(arg1) {
  return window['go']['keys']['KeyRetrieve']['DeleteSymKey'](arg1);
}

export function GetEncryptionFromSignature(arg1) {
  return window['go']['keys']['KeyRetrieve']['GetEncryptionFromSignature'](arg1);
}

export function LoadAsymmetricEnData(arg1) {
  return window['go']['keys']['KeyRetrieve']['LoadAsymmetricEnData'](arg1);
}

export function LoadEncryptedKeyContent(arg1) {
  return window['go']['keys']['KeyRetrieve']['LoadEncryptedKeyContent'](arg1);
}

export function RetrieveAsymmetricKeys() {
  return window['go']['keys']['KeyRetrieve']['RetrieveAsymmetricKeys']();
}

export function RetrievePgpKeys() {
  return window['go']['keys']['KeyRetrieve']['RetrievePgpKeys']();
}

export function RetrievePgpPrivKey(arg1) {
  return window['go']['keys']['KeyRetrieve']['RetrievePgpPrivKey'](arg1);
}

export function RetrievePgpPubKey(arg1) {
  return window['go']['keys']['KeyRetrieve']['RetrievePgpPubKey'](arg1);
}

export function RetrieveSymmetricKeys() {
  return window['go']['keys']['KeyRetrieve']['RetrieveSymmetricKeys']();
}
