// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RetrieveAsymmetricKeys():Promise<Array<string>>;

export function RetrieveSymmetricKeys():Promise<Array<string>>;
