// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadEncryptedKeyContent(arg1, arg2) {
  return window['go']['keys']['KeyRetrieve']['LoadEncryptedKeyContent'](arg1, arg2);
}

export function RetrieveAsymmetricKeys() {
  return window['go']['keys']['KeyRetrieve']['RetrieveAsymmetricKeys']();
}

export function RetrieveSymmetricKeys() {
  return window['go']['keys']['KeyRetrieve']['RetrieveSymmetricKeys']();
}
