// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keys} from '../models';

export function RetrieveAsymmetricKeys():Promise<Array<keys.KeyInfo>>;

export function RetrieveSymmetricKeys():Promise<Array<keys.KeyInfo>>;
