// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveAsymmetricData(arg1) {
  return window['go']['keys']['KeyStore']['SaveAsymmetricData'](arg1);
}

export function SaveSymmetricKey(arg1, arg2, arg3) {
  return window['go']['keys']['KeyStore']['SaveSymmetricKey'](arg1, arg2, arg3);
}
