// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveAsymmetricKey(arg1, arg2, arg3, arg4) {
  return window['go']['keys']['KeyStore']['SaveAsymmetricKey'](arg1, arg2, arg3, arg4);
}

export function SaveSymmetricKey(arg1, arg2, arg3, arg4) {
  return window['go']['keys']['KeyStore']['SaveSymmetricKey'](arg1, arg2, arg3, arg4);
}
