// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keys} from '../models';

export function SaveAsymmetricData(arg1:keys.HybridRequestData):Promise<void>;

export function SaveSymmetricKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
