// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keys} from '../models';

export function DecryptPgpPrivKey(arg1:string,arg2:string):Promise<string>;

export function GenECC(arg1:keys.RequestData):Promise<keys.ReturnType>;

export function GenRSA(arg1:keys.RequestData):Promise<keys.ReturnType>;

export function GenStoreECC(arg1:keys.RequestData):Promise<keys.ReturnType>;

export function GenStoreRSA(arg1:keys.RequestData):Promise<keys.ReturnType>;

export function GeneratePGPKeys(arg1:keys.RequestData):Promise<keys.ReturnType>;
