// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptPgpPrivKey(arg1, arg2) {
  return window['go']['keys']['PgpKeysGen']['DecryptPgpPrivKey'](arg1, arg2);
}

export function GenECC(arg1) {
  return window['go']['keys']['PgpKeysGen']['GenECC'](arg1);
}

export function GenRSA(arg1) {
  return window['go']['keys']['PgpKeysGen']['GenRSA'](arg1);
}

export function GenStoreECC(arg1) {
  return window['go']['keys']['PgpKeysGen']['GenStoreECC'](arg1);
}

export function GenStoreRSA(arg1) {
  return window['go']['keys']['PgpKeysGen']['GenStoreRSA'](arg1);
}

export function GeneratePGPKeys(arg1) {
  return window['go']['keys']['PgpKeysGen']['GeneratePGPKeys'](arg1);
}
