// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptPgpPrivKey(arg1, arg2) {
  return window['go']['keys']['PgpKeysGen']['DecryptPgpPrivKey'](arg1, arg2);
}

export function GeneratePGPKeys(arg1) {
  return window['go']['keys']['PgpKeysGen']['GeneratePGPKeys'](arg1);
}
