// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keys} from '../models';

export function DecryptPgpPrivKey(arg1:string,arg2:string):Promise<string>;

export function GeneratePrivatePublicKeys(arg1:keys.RequestData):Promise<keys.ReturnType>;
