// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptPrivKey(arg1, arg2) {
  return window['go']['keys']['PubPrvKeyGen']['DecryptPrivKey'](arg1, arg2);
}

export function GeneratePrivatePublicKeys(arg1) {
  return window['go']['keys']['PubPrvKeyGen']['GeneratePrivatePublicKeys'](arg1);
}

export function RetrievePrivKey(arg1) {
  return window['go']['keys']['PubPrvKeyGen']['RetrievePrivKey'](arg1);
}

export function RetrievePubKey(arg1) {
  return window['go']['keys']['PubPrvKeyGen']['RetrievePubKey'](arg1);
}
