// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptPrivKey(arg1) {
  return window['go']['keys']['PubPrvKeyGen']['DecryptPrivKey'](arg1);
}

export function GeneratePrivatePublicKeys(arg1) {
  return window['go']['keys']['PubPrvKeyGen']['GeneratePrivatePublicKeys'](arg1);
}

export function RetrievePrivKey() {
  return window['go']['keys']['PubPrvKeyGen']['RetrievePrivKey']();
}

export function RetrievePubKey() {
  return window['go']['keys']['PubPrvKeyGen']['RetrievePubKey']();
}
