// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keys} from '../models';

export function DecryptPrivKey(arg1:string,arg2:string):Promise<string>;

export function GeneratePrivatePublicKeys(arg1:keys.RequestData):Promise<keys.ReturnType>;

export function RetrievePrivKey(arg1:string):Promise<string>;

export function RetrievePubKey(arg1:string):Promise<string>;
