// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {symmetricencryption} from '../models';

export function EncryptAES(arg1:symmetricencryption.RequestData):Promise<string>;
