// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hybridencryption} from '../models';

export function EncryptSharedData(arg1:hybridencryption.RequestData):Promise<string>;
