// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EncryptSharedData(arg1) {
  return window['go']['hybridencryption']['HybridEncryption']['EncryptSharedData'](arg1);
}

export function PerformHybridEnOnExistingData(arg1) {
  return window['go']['hybridencryption']['HybridEncryption']['PerformHybridEnOnExistingData'](arg1);
}
