// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HybEn(arg1) {
  return window['go']['hybridencryption']['HybridEncryption']['HybEn'](arg1);
}

export function TrasformHybEn(arg1) {
  return window['go']['hybridencryption']['HybridEncryption']['TrasformHybEn'](arg1);
}
