// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hybridencryption} from '../models';

export function HybEn(arg1:hybridencryption.RequestData):Promise<string>;

export function TrasformHybEn(arg1:hybridencryption.RequestData):Promise<string>;
