// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1, arg2) {
  return window['go']['filesystem']['Folder']['CreateFile'](arg1, arg2);
}

export function GetFolderPath() {
  return window['go']['filesystem']['Folder']['GetFolderPath']();
}

export function ListFiles() {
  return window['go']['filesystem']['Folder']['ListFiles']();
}

export function RemoveFile(arg1) {
  return window['go']['filesystem']['Folder']['RemoveFile'](arg1);
}

export function SelectFolder() {
  return window['go']['filesystem']['Folder']['SelectFolder']();
}

export function SetContext(arg1) {
  return window['go']['filesystem']['Folder']['SetContext'](arg1);
}

export function UpdateFolderPath(arg1) {
  return window['go']['filesystem']['Folder']['UpdateFolderPath'](arg1);
}
