// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function GetFolderPath():Promise<string>;

export function ListFiles():Promise<Array<string>>;

export function RemoveFile(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateFolderPath(arg1:string):Promise<void>;
