// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cryptography} from '../models';

export function EncryptAES(arg1:cryptography.RequestData):Promise<string>;
