// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {symmetricdecryption} from '../models';

export function AES128Decryption(arg1:symmetricdecryption.DataToDecrypt):Promise<string>;

export function AES192Decryption(arg1:symmetricdecryption.DataToDecrypt):Promise<string>;

export function AES256Decryption(arg1:symmetricdecryption.DataToDecrypt):Promise<string>;
